<?php
//require_once "/home/conamore/www/loja/krumo/class.krumo.php"; 

// SE NAO SETAR O VALOR DA VARIAVEL ABAIXO OS CAMPOS DE ENDERECO NAO APARECEM ASSIM COMO SE FOR 
// REMOVIDO O IF QUE FAZ COM QUE ELES NAO APARECAO OS ESTADOS TB NAO SAO CARREGADOS
//$this->setShowAddressFields(true);

/*
    $setup = new Mage_Eav_Model_Entity_Setup('core_setup');
    $AttrCode = 'custom_rg';
    $settings = array (
        'position' => 1,
        'is_required'=> 1,
		  'frontend_label' =>"RG"
    );
    $setup->addAttribute('1', $AttrCode, $settings);

$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
$setup->addAttribute('customer', 'customcpf', array(
	'label'		=> 'CPF',
	'type'		=> 'varchar',
	'input'		=> 'text',
	'visible'	=> true,
	'required'	=> true,
	'position'	=> 3,
	));
$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
$setup->addAttribute('customer_address', 'bairro', array(
      'label'    => 'Bairro',
      'type'     => 'varchar',
      'input'    => 'text',
      'is_user_defined'   => 1,
      'is_system'         => 0,
      'is_visible'        => 1,
      'sort_order'        => 140,
      'is_required'       => 1,
      'multiline_count'   => 0,
      'validate_rules'    => array(
          'max_text_length'   => 255,
          'min_text_length'   => 1
      ),
	));
*/ 
//$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
//$setup->removeAttribute('1', 'customrg');
//$headBlock = $this->getLayout()->getBlock('head');
//$headBlock->addJs('/home/conamore/www/loja/js/conamore/funcoes.js');
//krumo($this);

//krumo($headBlock);


  ?>
<?php
/**
 * /www/loja/app/design/frontend/base/default/template/customer/form
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * /www/loja/app/design/frontend/base/default/template/customer/form
 * Create account form template
 *
 * @see Mage_Customer_Block_Form_Register
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
					<li>
						<div class="input-box">
						  <label for="customrg" class="required"><em>*</em><?php echo $this->__('RG') ?></label><br/>
						  <input type="text" name="customrg" id="customrg" value="<?php echo $this->htmlEscape($this->getFormData()->getCustomrg()) ?>" title="<?php echo $this->__('RG') ?>" class="input-text validate-customrg validate-digits required-entry" />
						</div>
					</li>
					<li>
						<div class="input-box">
						  <label for="customcpf" class="required"><em>*</em><?php echo $this->__('CPF') ?></label><br/>
						  <input type="text" name="customcpf" id="customcpf" value="<?php echo $this->htmlEscape($this->getFormData()->getCustomcpf()) ?>" title="<?php echo $this->__('CPF') ?>" class="input-text validate-digits validar_cpf required-entry" />
						</div>
						<script type="text/javascript">
							 //<![CDATA[
							 // Adicionar classe de validação de cpf e cnpj
							 //$('customcpf').addClassName('validar_cpf');
							 Validation.add('validar_cpf', 'O CPF informado \xE9 invalido', function(v){return conamoreValidaCPF(v,1);});
							 //]]>
						 </script>
					</li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
					<li>
					 <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
					</li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
		          <li class="control">
		              <div class="input-box">
		                  <input type="checkbox" name="show_comercial_data" title="Mostar dados Comerciais" onchange="showComercial();" value="" id="show_comercial_data"  class="checkbox" />
		              </div>
		              <label for="show_comercial_data">Mostar dados Comerciais</label>
		          </li>
            </ul>
        </div>
        <div id="dados_comercias" class="fieldset" style="display:none;">
            <h2 class="legend"><?php echo $this->__('Dados Comercias') ?></h2>
            <ul class="form-list">
					<li>
						<div class="input-box">
						  <label for="customcnpj" ><?php echo $this->__('CNPJ') ?></label><br/>
						  <input type="text" name="customcnpj" id="customcnpj" value="<?php echo $this->htmlEscape($this->getFormData()->getCustomcnpj()) ?>" title="<?php echo $this->__('CNPJ') ?>" class="input-text" />
						</div>
						<script type="text/javascript">
							 //<![CDATA[
							 // Adicionar classe de validação de e cnpj
							 $('customcnpj').addClassName('validar_cnpj');
							 Validation.add('validar_cnpj', 'O CNPJ informado \xE9 invalido', function(v){return conamoreValidaCPF(v,2);});
							 //]]>
						 </script>
					</li>
					<li>
						<div class="input-box">
						  <label for="razaosocial"><?php echo $this->__('Razão Social') ?></label><br/>
						  <input type="text" name="razaosocial" id="razaosocial" value="<?php echo $this->htmlEscape($this->getFormData()->getRazaosocial()) ?>" title="<?php echo $this->__('Razão Social') ?>" class="input-text" />
						</div>
					</li>
					<li>
						<div class="input-box">
						  <label for="inscricaoestadual"><?php echo $this->__('Inscrição Estadual') ?></label><br/>
						  <input type="text" name="inscricaoestadual" id="inscricaoestadual" value="<?php echo $this->htmlEscape($this->getFormData()->getInscricaoestadual()) ?>" title="<?php echo $this->__('Inscrição Estadual') ?>" class="input-text" />
						</div>
					</li>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                </li>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
						<li class="fields">
							 <div class="field">
								  <label for="bairro" class="required"><em>*</em><?php echo $this->__('Bairro') ?></label>
								  <div class="input-box">
										<input type="text" name="bairro" value="<?php echo $this->htmlEscape($this->getAddress()->getBairro()) ?>"  title="<?php echo $this->__('Bairro') ?>" class="input-text required-entry" id="bairro" />
								  </div>
							 </div>
						</li>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                        </div>
                    </div>
							<div class="field">
							  <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
							  <div class="input-box">
									<select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
										<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
									</select>
									<script type="text/javascript">
									//<![CDATA[
										 $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
									//]]>
									</script>
									<input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" />
							  </div>
							</div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
